### ISSUE TITLE
organize data as archive/{timestamp}/{table}.csv

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/coronaDAT#1]
To make this repo more accessible for other (non-R) projects, it might be a good idea to follow the recommendations in https://twitter.com/botic/status/1241810134520774657

this would make it possible to implement fast functions in `coronaAT`
- `plot_map(timestamp = "latest")`
- `plot_confirmed_bl(timestamp = "latest")`

I'd also put the latest data into a separate folder (`archive/latest`) so it can be fetched easily without a logic that determines the last available timestamp

@bernhard-da let's talk about this in detail at the next webex meeting.

**Comment by bernhard-da** [comment]
fixed with e8b444fcac1b368d9e791bf975cff3b2a7742f36

it would also be (quite easily) possible to add all historical data (e.g the one shared by you) to the repo if we want to do that.
