### ISSUE TITLE
Missing files in data archive 3.11 and 4.11

### ISSUE THREAD

**Issue by co-miko** [statistikat/coronaDAT#11]
Thank you for your work in gathering all the data.

In the last datasets I found out that there are missing files, especially:
Bundesland.csv
Bezirke.csv
AllgemeinDaten.csv

Is it possible to add them again? Our website relies on those files to show the information:
https://covid.lanthaler.com/AT/

sincerely
Michael

**Comment by bernhard-da** [comment]
@co-miko thx for the report; however this is what is officially published; ages obviously decided to change the files they are releasing.
