### ISSUE TITLE
Include vaccinations per municipality

### ISSUE THREAD

**Issue by Oberon00** [statistikat/coronaDAT#12]
Hello! First, thank you for this very useful repository!

For the issue: It would be cool if a daily download of https://www.data.gv.at/katalog/dataset/covid-19-schutzimpfungen-impfungen-in-gemeinden would be included in the data here.

If there is a repository with the source code for the downloader (assuming it's automated), I'd be happy to contribute.

**Comment by bernhard-da** [comment]
hi @Oberon00 

good idea and already implemented; data are regularly scraped and updated in `
https://github.com/statistikat/coronaDAT/blob/master/archive/{ymd}/data/{timestamp}_impfdaten_orig_csv_bmsgpk.zip`
