### ISSUE TITLE
Genesene Personen

### ISSUE THREAD

**Issue by ghost** [statistikat/coronaDAT#3]
Ist es viellicht möglich Genesene Personen (nach Bundesland) auch zu scrapen?
Eventuell gibts ja auch noch wo die historischen Daten?

**Comment by bernhard-da** [comment]
@hagabla meines wissens nach werden diese daten nicht offiziell publiziert. hast du eine quelle?

**Comment by ghost** [comment]
https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html


`Genesen, Stand 02.04.2020, 09:30 Uhr: 1.749, nach Bundesländern: Burgenland (21), Kärnten (51), Niederösterreich (298), Oberösterreich (371), Salzburg (130), Steiermark (99), Tirol (546), Vorarlberg (147), Wien (86).`

**Comment by bernhard-da** [comment]
@hagabla danke, ich scrape die seite jetzt mal und schreibe die daten in

- `archive/{day}/data/{ts}_gesundungen_todesfaelle.rds`
- `latest/sterbefaelle_bl.{csv|rds|json}`
- `latest/gesundungen_bl.{csv|rds|json}`
- `ts/sterbefaelle_bl.{csv|rds|json}`
- `ts/gesundungen_bl.{csv|rds|json}`

das sollte man zwar mit den normalen bundeslaenderreihen kombinieren (die `allgemein.xyz`), aber nachdem sich auf der verlinkten seite moeglicherweise timestamps, ... aendern, lass ich das erst mal. das kann man später immer noch machen.

**Comment by bernhard-da** [comment]
@hagabla danke, ich scrape die seite jetzt mal und schreibe die daten in

- `archive/{day}/data/{ts}_gesundungen_todesfaelle.rds`
- `latest/sterbefaelle_bl.{csv|rds|json}`
- `latest/gesundungen_bl.{csv|rds|json}`
- `ts/sterbefaelle_bl.{csv|rds|json}`
- `ts/gesundungen_bl.{csv|rds|json}`

das sollte man zwar mit den normalen bundeslaenderreihen kombinieren (die `allgemein.xyz`), aber nachdem sich auf der verlinkten seite moeglicherweise timestamps, ... aendern, lass ich das erst mal. das kann man später immer noch machen.
