### ISSUE TITLE
CSV auch mit Komma, nicht nur mit Semicolon?

### ISSUE THREAD

**Issue by neuwirthe** [statistikat/coronaDAT#4]
Github kann „angelsächsische“ CSV-Dateien (comma separated) im Browser auch in Tabellenform darstellen, die „deutschen“ (mit Semikolon) aber nicht. Wäre es zu viel Mühe, beide Varianten anzubieten? Vielleicht in getrennten Unterverzeichnissen?

**Comment by bernhard-da** [comment]
hallo @neuwirthe ich schreibe jetzt einmal die csv's mit `,` als separator mit suffix `*_en.csv` in die entsprechendenv verzeichnisse. möglicherweise werden wir das aber in zukunft aendern und ueberhaupt nur die "angelsächsische" variante anbieten. das einlesen in software ist ja trivial und wenns um die ansicht in github geht haben sie natuerlich recht, dass das so besser ist.

**Comment by neuwirthe** [comment]
Die "deutschen" sind sinnvoll für Leute, die die Daten in einer deutsch konfigurierten Maschine in Excel einlesen wollen. Excel mit "fremdsprachigen“ CSVs ist ziemlich mühsam.
