### ISSUE TITLE
Suggestion improvement Readme file

### ISSUE THREAD

**Issue by mvanreek** [statistikat/coronaDAT#7]
In the Readme file, I would do the update-log in descending order, so most recent change on top.

**Comment by bernhard-da** [comment]
@mvanreek thx for the suggestion which is of course a good idea; done

**Comment by mvanreek** [comment]
and another suggestion would be to have also English documentation  ;) I understand German quite well, but I doub what you mean with: 'gescrapten Daten'. You have actual version and timeseries (history of 'old actual versions'), but the 'gescrapten Daten' category.., not clear to me.
Anyway, good work, this repo! 

Ps: if you want to see more Open Data Github COVID-19 repo's, and how I visualized them with Power BI, see:

[http://worktimesheet2014.blogspot.com/2020/03/covid-19-analysis-of-number-of-deaths.html](http://worktimesheet2014.blogspot.com/2020/03/covid-19-analysis-of-number-of-deaths.html)

**Comment by bernhard-da** [comment]
@mvanreek i agree, i rewrote the readme in english.
