### ISSUE TITLE
Codebook in English

### ISSUE THREAD

**Issue by 4tikhonov** [statistikat/coronaDAT#8]
Hi coronaDAT team,

Great work, thanks! Can you please add a basic codebook with the explanation of all your variables?

You can find an example below how they do it in Spain:
Campo | Descripción | Description | Formato | Ejemplo
https://github.com/datadista/datasets/tree/master/COVID%2019

It can help to standardize the data and reuse in a number of data analysis tools.

**Comment by bernhard-da** [comment]
hi @4tikhonov i have added (in the readme) some descriptions. hope that it helps.
