### ISSUE TITLE
FehlendeBezirke

### ISSUE THREAD

**Issue by neuwirthe** [statistikat/coronaDAT#9]
102 Rust und
104 Güssing fehlen.
Wo sind die dazugeschlagen.

**Comment by bernhard-da** [comment]
@neuwirthe also Güssing (104) kommt in den Zeitreihen schon vor und Rust (102) wird nicht publiziert. Ob es keine Fälle gibt oder das andere Gründe hat, weiß ich nicht. Aber auch im Dashboard fehlt dieser Bezirk.

**Comment by neuwirthe** [comment]
Noch eine Frage: Sind die Sterbefälle
sterbefaelle_bl
kumulierte Zahlen?. Das scheint vernünftig.

Die Hospitalisierten und die Intensivpatienten aber jeweils die Tagesaktuellen?

**Comment by bernhard-da** [comment]
@neuwirthe die todesfälle und genesungen scrapen wir von [`hier`](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html) und die daten über hospitalisierungen bzw. menschen in intensivbetreuung von [`dieser seite`](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Dashboard/Zahlen-zur-Hospitalisierung). diese zahlen werden *"as-is"* genommen und unveraendert abgespeichert.

**Comment by neuwirthe** [comment]
Werden sie weiterscrapen.
Bundesländerweise Fallzahlen-Zeitreihe gibts im dashboard nämlich nicht zum download.

Mit freundlichen Grüßen

Erich Neuwirth

**Comment by bernhard-da** [comment]
@neuwirthe ich scrape vorerst einmal nur die datenfiles. ich hoffe aber, dass ich bald einmal dazukomme, die zeitreihen wieder zu aktualisieren, versprechen kann und will ich aber nichts. ich hoffe ja doch stark, dass in absehbarer zeit auch die zeitreihen im opendata-portal verfuegbar sein werden und damit dieses repo obsolet wird.
